name: Sync Parent → Child

on:
  push:
    branches:
      - main

jobs:
  sync-to-child:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ParentRepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone ChildRepo sync branch
        env:
          CHILD_REPO_SECRET: ${{ secrets.CHILD_REPO_SECRET }}
        run: |
          git clone https://x-access-token:${CHILD_REPO_SECRET}@github.com/kvivekkannan/ChildRepo.git childrepo
          cd childrepo
          git checkout sync-branch || git checkout -b sync-branch
          git config user.name "kvivekkannan"
          git config user.email "kviveknishanth@gmail.com"

      - name: Copy files from ParentRepo to ChildRepo
        run: |
          rsync -av --exclude='.git' ./ ./childrepo/
          cd childrepo
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Sync from ParentRepo main at ${{ github.sha }}" 
            git push origin sync-branch
          else
            echo "No changes to sync"
          fi
